#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing git ..."
  brew install git

echo "Installing mysql ..."
  brew install mysql

echo "Installing node js ..."
  brew install node

echo "Installing npm ..."
  curl http://npmjs.org/install.sh | clean=yes sh

echo "Installing rvm ..."
  curl -L get.rvm.io | bash -s stable
  source ~/.rvm/scripts/rvm
  
echo "Installing ruby 1.9.3"
  rvm install 1.9.3
