#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing git ..."
  brew install git

echo "Installing mysql ..."
  brew install mysql

echo "Installing node js ..."
  brew install node

echo "Installing npm ..."
  curl http://npmjs.org/install.sh | clean=yes sh

echo "Installing rbenv ..."
  brew install rbenv
  echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  source ~/.bash_profile


echo "Installing ruby-build"
  brew install ruby-build


echo 

bash < <(curl -s https://raw.github.com/ready4god2513/laptop/master/ruby)
